server:
  port: 8081

spring:
  rabbitmq:
    routing-key: rk.consumer.rabbitmq

api:
  transactions:
    endpoint: http://localhost:8080/transactions
  currentAccount:
    endpoint: http://localhost:8080/currentAccount